### ISSUE TITLE
Error: $ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by chubbar1963** [jtextor/dagitty#23] opened 2019-07-02 18:25 UTC
When I run the dagitty function, I get the following error code:

Error: $ operator is invalid for atomic vectors

For example, the following is taken from the dagitty documentation::

```
g <- dagitty("dag{ 
  a -> b ;
  b -> c ;
  d -> c
 }")
```

> Error: $ operator is invalid for atomic vectors

Traceback:

> 6. stop(e)
> 5. value[[3L]](cond)
> 4. tryCatchOne(expr, names, parentenv, handlers[[1L]])
> 3. tryCatchList(expr, classes, parentenv, handlers)
> 2. tryCatch({ .jsassign(xv, as.character(x)) .jsassign(xv, .jsp("GraphParser.parseGuess(global.", xv, ").toString()")) ...
> 1. dagitty("dag{ \n a -> b ;\n b -> c ;\n d -> c\n }")

Any thoughts?  Thanks!

**Comment by jtextor** [comment] 2019-07-05 07:09
Thank you for your message. I am afraid I cannot reproduce this problem, when I paste this code into R it works just fine. Can you please tell me more about your environment, e.g., what does "packageVersion('dagitty')" say and which version of R are you running?

**Comment by chubbar1963** [comment] 2019-07-08 15:56
Here you go.  Thanks!

> packageVersion('dagitty')

[1] ‘0.2.2’

> R.Version()

$platform
[1] "x86_64-w64-mingw32"

$arch
[1] "x86_64"

$os
[1] "mingw32"

$system
[1] "x86_64, mingw32"

$status
[1] ""

$major
[1] "3"

$minor
[1] "6.0"

$year
[1] "2019"

$month
[1] "04"

$day
[1] "26"

$`svn rev`
[1] "76424"

$language
[1] "R"

$version.string
[1] "R version 3.6.0 (2019-04-26)"

$nickname
[1] "Planting of a Tree"

**Comment by jtextor** [comment] 2019-07-08 18:22
So you're using this on MinGW is that correct? I've never tried that TBH. I have a feeling that the V8 package might be the problem, it's a dependency and it's fairly complex. What do you get when you run "packageVersion('v8')" ?

**Comment by chubbar1963** [comment] 2019-07-09 15:28
> packageVersion('v8')

[1] ‘2.2’

As for MinGW, I don't really know.  I thought I was running Windows 10

Here's what I get when I open System Information:

> OS Name	Microsoft Windows 10 Enterprise
> Version	10.0.17763 Build 17763

**Comment by jtextor** [comment] 2019-09-30 20:53
I believe this issue should be fixed now (see related issue #24). Closing it for now.

**Closed by jtextor** 2019-09-30 20:53 UTC

**Comment by dibatti5** [comment] 2023-05-14 21:59
Im still having this issue, has there been a resolution?
